// apps/web/src/routes/dashboard/_components/SidebarLink.svelte
<script lang="ts">
    import { cn } from '@sathene/ui'

    import { page } from '$app/state'
    import type { DashboardLink } from '$lib/consts'

    interface Props {
        link: DashboardLink
    }

    let { link }: Props = $props()
</script>

<a
    href={link.href}
    class={cn(
        'flex items-center gap-2 rounded-md p-2',
        page.url.pathname.includes(link.href)
            ? 'bg-primary text-primary-foreground'
            : 'hover:bg-primary/25'
    )}
>
    {@render link.icon({ class: 'h-5 w-5' })}
    <span>{link.title}</span>
</a>

// apps/web/app/dashboard/_components/SidebarLink.tsx
'use client'

import { usePathname, useRouter } from 'next/navigation'

import { cn } from '@sathene/ui-web'

import type { DashboardLink } from '~/lib/consts'

interface Props {
    link: DashboardLink
    onClick?: () => void
}

export function DashboardSidebarLink({ link, onClick }: Props) {
    const pathname = usePathname()
    const router = useRouter()

    const Icon = link.icon

    const handleClick = () => {
        if (onClick) {
            onClick()
        } else if (link.href) {
            router.push(link.href)
        }
    }

    return (
        <button
            className={cn(
                'flex items-center gap-2 h-12 w-full rounded-xl px-4 font-bold',
                pathname.includes(link.href as string)
                    ? 'bg-primary text-background'
                    : 'hover:bg-primary/25'
            )}
            onClick={handleClick}
            key={link.title}
        >
            <Icon />

            {link.title}
        </button>
    )
}
