// apps/web/src/routes/dashboard/_components/Sidebar.svelte
<script lang="ts">
    import { DASHBOARD_LINKS } from '$lib/consts'

    import SidebarLink from './SidebarLink.svelte'
</script>

<div class="bg-accent border-r-border flex w-64 flex-col border-r p-4">
    <div class="mb-2">
        <a href="/" class="mr-2 text-2xl font-bold">Sathene</a>
    </div>

    <div class="flex flex-col gap-2">
        {#each DASHBOARD_LINKS as link}
            <SidebarLink {link} />
        {/each}
    </div>

    <div class="mt-auto"></div>
</div>

// apps/web/app/dashboard/notes/_components/Sidebar.tsx
import { DashboardNotesCreateNoteButton } from './CreateNoteButton'
import { DashboardNotesSidebarLink } from './SidebarLink'
import { caller } from '~/lib/caller'

export async function DashboardNotesSidebar() {
    const notes = await caller.note.all()

    return (
        <div className="flex flex-col bg-accent border-r overflow-auto">
            <DashboardNotesCreateNoteButton />

            <div className="flex flex-col gap-2 overflow-scroll">
                {notes.map((note) => (
                    <DashboardNotesSidebarLink note={note} key={note.id} />
                ))}
            </div>
        </div>
    )
}
