// apps/web/app/dashboard/settings/_components/SidebarLink.tsx
'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'

import { cn } from '@sathene/ui-web'

import type { DashboardLink } from '~/lib/consts'

interface Props {
    link: DashboardLink
}

export function DashboardSidebarLink({ link }: Props) {
    const pathname = usePathname()

    const Icon = link.icon

    return (
        <Link
            className={cn(
                'flex items-center gap-2 h-10 w-full rounded-xl px-3 text-sm font-bold',
                pathname.includes(link.href as string) ? 'bg-primary/20' : 'hover:bg-primary/20'
            )}
            href={link.href ?? ''}
            key={link.title}
        >
            <Icon />

            {link.title}
        </Link>
    )
}

// apps/web/src/routes/dashboard/_components/SidebarLink.svelte
<script lang="ts">
    import { cn } from '@sathene/ui'

    import { page } from '$app/state'
    import type { DashboardLink } from '$lib/consts'

    interface Props {
        link: DashboardLink
    }

    let { link }: Props = $props()
</script>

<a
    href={link.href}
    class={cn(
        'flex items-center gap-2 rounded-md p-2',
        page.url.pathname.includes(link.href)
            ? 'bg-primary text-primary-foreground'
            : 'hover:bg-primary/25'
    )}
>
    {@render link.icon({ class: 'h-5 w-5' })}
    <span>{link.title}</span>
</a>
