// apps/web/src/routes/dashboard/calendar/_components/MonthView.svelte
<script lang="ts">
    import { type Dayjs, dayjs } from '@sathene/dayjs'
    import { cn } from '@sathene/ui'

    import { date as globalDate } from '$lib/stores/date.svelte'

    interface FormattedDate {
        date: Dayjs
        isThisMonth: boolean
        isToday: boolean
    }

    let month: FormattedDate[][] = $state([])

    $effect(() => {
        createMonth()
    })

    function createMonth() {
        let currentDate = globalDate.value.startOf('month').weekday(0)
        const nextMonth = globalDate.value.add(1, 'month').month()
        let allDates = []
        let weekDates = []
        let weekCounter = 1
        while (currentDate.weekday(0).month() !== nextMonth) {
            const formatted = formatDateObject(currentDate)
            weekDates.push(formatted)
            if (weekCounter === 7) {
                allDates.push(weekDates)
                weekDates = []
                weekCounter = 0
            }
            weekCounter++
            currentDate = currentDate.add(1, 'day')
        }

        month = allDates
    }

    function formatDateObject(date: Dayjs): FormattedDate {
        return {
            date,
            isThisMonth: date.month() === globalDate.value.month(),
            isToday: date.isToday()
        }
    }

    function checkDateIsSame(firstDate: Dayjs, secondDate: Dayjs): boolean {
        return (
            firstDate.date() === secondDate.date() &&
            firstDate.month() === secondDate.month() &&
            firstDate.year() === secondDate.year()
        )
    }
</script>

<div class="flex h-full flex-col">
    <div class="flex w-full items-center justify-center">
        {#each dayjs.weekdaysShort(true) as day}
            <p class="flex h-8 w-full items-center justify-center border-r text-xs uppercase">
                {day}
            </p>
        {/each}
    </div>

    <div class="grid h-full flex-1 border-t border-r border-b">
        {#each month as week, i}
            <div class="flex h-full">
                {#each week as day, j}
                    <div
                        class={cn(
                            'relative flex w-full flex-col gap-2 border-r border-b py-1 transition-none',
                            !day.isThisMonth && 'bg-accent opacity-50',
                            j === 6 && 'border-r-0',
                            i === month.length - 1 &&
                                'border-b-0 first:rounded-bl-xl last:rounded-br-xl'
                        )}
                    >
                        {#if day.isToday}
                            <div
                                class="bg-primary absolute top-0.5 right-0 left-0 mr-auto ml-auto h-7 w-7 rounded-full"
                            ></div>
                        {/if}

                        {#if checkDateIsSame(day.date, globalDate.value)}
                            <div
                                class="bg-primary absolute top-0.5 right-0 left-0 mr-auto ml-auto h-7 w-7 rounded-full"
                            ></div>
                        {/if}

                        <p
                            class={cn(
                                'z-10 flex h-6 w-full items-center justify-center text-sm',
                                checkDateIsSame(day.date, globalDate.value) &&
                                    'text-primary-foreground'
                            )}
                        >
                            {day.date.date()}
                        </p>
                    </div>
                {/each}
            </div>
        {/each}
    </div>
</div>

// apps/web/app/dashboard/calendar/_components/MonthView.tsx
'use client'

import { useEffect, useState } from 'react'

import { dayjs, type Dayjs } from '@sathene/dayjs'
import { cn } from '@sathene/ui-web'

import { useDate } from '~/hooks/useDate'

interface FormattedDate {
    date: Dayjs
    isThisMonth: boolean
    isToday: boolean
}

interface Props {
    onDayClick?: (day: FormattedDate) => void
}

export function DashboardCalendarMonthView({ onDayClick }: Props) {
    const { date: globalDate } = useDate()
    const [month, setMonth] = useState<FormattedDate[][]>([])

    useEffect(() => {
        createMonth()
    }, [globalDate])

    const createMonth = () => {
        let currentDate = globalDate.startOf('month').weekday(0)
        const nextMonth = globalDate.add(1, 'month').month()
        let allDates = []
        let weekDates = []
        let weekCounter = 1
        while (currentDate.weekday(0).month() !== nextMonth) {
            const formated = formatDateObject(currentDate)
            weekDates.push(formated)
            if (weekCounter === 7) {
                allDates.push(weekDates)
                weekDates = []
                weekCounter = 0
            }
            weekCounter++
            currentDate = currentDate.add(1, 'day')
        }

        setMonth(allDates)
    }

    const formatDateObject = (date: Dayjs): FormattedDate => {
        const formatedObj: FormattedDate = {
            date,
            isThisMonth: globalDate.month() === date.month(),
            isToday: date.isToday()
        }
        return formatedObj
    }

    const checkDateIsSame = (firstDate: Dayjs, secondDate: Dayjs): boolean => {
        if (
            firstDate.date() === secondDate.date() &&
            firstDate.month() === secondDate.month() &&
            firstDate.year() === secondDate.year()
        ) {
            return true
        } else return false
    }

    return (
        <div className="flex flex-col h-full">
            <div className="flex justify-center items-center w-full bg-accent rounded-t-xl">
                {dayjs.weekdaysMin(true).map((day) => (
                    <p
                        className="flex justify-center items-center h-8 w-full uppercase text-xs"
                        key={day}
                    >
                        {day}
                    </p>
                ))}
            </div>

            <div className="grid flex-1 h-full border rounded-b-xl">
                {month.map((week, i) => (
                    <div className="flex h-full" key={i}>
                        {week.map((day, j) => (
                            <div
                                className={cn(
                                    'relative flex flex-col gap-2 w-full bg-accent py-1 border-r border-b',
                                    !day.isThisMonth && 'opacity-75 bg-muted',
                                    j === 6 && 'border-r-0',
                                    i === month.length - 1 &&
                                        'border-b-0 first:rounded-bl-xl last:rounded-br-xl',
                                    onDayClick && 'cursor-pointer hover:bg-primary/25'
                                )}
                                key={j}
                                onClick={() => (onDayClick ? onDayClick(day) : null)}
                            >
                                {day.isToday && (
                                    <div className="absolute top-0.5 left-0 right-0 bg-purple-500 rounded-full ml-auto mr-auto h-7 w-7"></div>
                                )}

                                {checkDateIsSame(day.date, globalDate) && (
                                    <div className="absolute top-0.5 left-0 right-0 bg-primary rounded-full ml-auto mr-auto h-7 w-7"></div>
                                )}

                                <p
                                    className={cn(
                                        'flex justify-center items-center text-sm h-6 w-full z-10',
                                        checkDateIsSame(day.date, globalDate) &&
                                            'text-primary-foreground'
                                    )}
                                >
                                    {day.date.date()}
                                </p>
                            </div>
                        ))}
                    </div>
                ))}
            </div>
        </div>
    )
}
