// packages/ui/web/src/components/input.tsx
import * as React from 'react'

import { cn } from '../lib/utils'
import { Label } from './label'

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
    label?: string
    error?: string
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
    ({ className, error, label, required, ...props }, ref) => {
        return (
            <div className="flex flex-col items-start gap-1 w-full">
                {label && (
                    <div className="flex justify-between w-full mb-1">
                        <Label className="flex items-center" htmlFor={label}>
                            {label}{' '}
                            {required && (
                                <span className="text-red-500 text-base leading-3">*</span>
                            )}
                        </Label>

                        {error && (
                            <p className="text-right text-sm text-red-500 leading-3 !mt-0">
                                {error}
                            </p>
                        )}
                    </div>
                )}

                <input
                    className={cn(
                        'flex h-10 w-full rounded-md border border-input bg-secondary px-3 py-2 text-sm ring-offset-secondary file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
                        className
                    )}
                    id={label}
                    ref={ref}
                    {...props}
                />
            </div>
        )
    }
)
Input.displayName = 'Input'

export { Input }

// packages/ui/src/components/input/input.svelte
<script lang="ts">
    import type { HTMLInputAttributes, HTMLInputTypeAttribute } from 'svelte/elements'

    import { type WithElementRef, cn } from '../../lib/utils.js'
    import { Label } from '../label/index.js'

    type InputType = Exclude<HTMLInputTypeAttribute, 'file'>

    type Props = WithElementRef<
        Omit<HTMLInputAttributes, 'type'> &
            ({ type: 'file'; files?: FileList } | { type?: InputType; files?: undefined }) & {
                label?: string
            }
    >

    let {
        ref = $bindable(null),
        value = $bindable(),
        type,
        files = $bindable(),
        class: className,
        label,
        'data-slot': dataSlot = 'input',
        ...restProps
    }: Props = $props()
</script>

{#if label}
    <Label class="mb-2" for={label}>{label}</Label>
{/if}
{#if type === 'file'}
    <input
        bind:this={ref}
        data-slot={dataSlot}
        id={label}
        name={label?.toLowerCase()}
        class={cn(
            'selection:bg-primary dark:bg-input/30 selection:text-primary-foreground border-input ring-offset-background placeholder:text-muted-foreground flex h-9 w-full min-w-0 rounded-md border bg-transparent px-3 pt-1.5 text-sm font-medium shadow-xs transition-[color,box-shadow] outline-none disabled:cursor-not-allowed disabled:opacity-50',
            'focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
            'aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive',
            className
        )}
        type="file"
        bind:files
        bind:value
        {...restProps}
    />
{:else}
    <input
        bind:this={ref}
        data-slot={dataSlot}
        id={label}
        name={label?.toLowerCase()}
        class={cn(
            'border-input bg-background selection:bg-primary dark:bg-input/30 selection:text-primary-foreground ring-offset-background placeholder:text-muted-foreground flex h-9 w-full min-w-0 rounded-md border px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
            'focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
            'aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive',
            className
        )}
        {type}
        bind:value
        {...restProps}
    />
{/if}
