// apps/web/app/dashboard/_modals/CreateTaskList.tsx
import { useRouter } from 'next/navigation'

import { Button, Input, useModals } from '@sathene/ui-web'

import { toast } from 'sonner'
import { z } from 'zod'
import { useZodForm } from '~/hooks/useZodForm'
import { api } from '~/lib/api'

const createTaskListSchema = z.object({
    name: z.string().min(3)
})
type CreateTaskListSchema = z.infer<typeof createTaskListSchema>

export function DashboardCreateTaskListModal() {
    const { closeAllModals } = useModals()
    const router = useRouter()

    const createTaskListMutation = api.task.list.create.useMutation()

    const {
        handleSubmit,
        register,
        formState: { errors }
    } = useZodForm({
        schema: createTaskListSchema
    })

    const handleCreateTaskList = (data: CreateTaskListSchema) => {
        createTaskListMutation.mutate(data, {
            onError: (err) => {
                toast.error(err.message)
            },
            onSuccess: () => {
                router.refresh()
                closeAllModals()
            }
        })
    }

    return (
        <form className="flex flex-col gap-4" onSubmit={handleSubmit(handleCreateTaskList)}>
            <Input
                label="Name"
                type="text"
                required
                error={errors.name?.message}
                {...register('name')}
            />

            <div className="grid grid-cols-2 gap-4 w-full">
                <Button type="button" variant="outline" onClick={closeAllModals}>
                    Cancel
                </Button>

                <Button type="submit" loading={createTaskListMutation.isLoading}>
                    Create
                </Button>
            </div>
        </form>
    )
}

// apps/web/src/routes/dashboard/_modals/CreateTaskList.svelte
<script lang="ts">
    import { Button, Input, buttonVariants } from '@sathene/ui'
    import { Dialog } from '@sathene/ui'

    import { api } from '$lib/api'
    import { closeAllModals } from '$lib/modals.svelte'
    import { errorHandler } from '$lib/utils'
    import { useQueryClient } from '@tanstack/svelte-query'
    import z from 'zod'

    const queryClient = useQueryClient()

    const schema = z.object({
        name: z.string().min(1)
    })

    let loading = $state(false)

    function handleCreateTaskList(e: SubmitEvent) {
        e.preventDefault()
        loading = true

        const form = new FormData(e.target as HTMLFormElement)
        const result = schema.safeParse(Object.fromEntries(form))

        if (!result.success) {
            loading = false
            throw errorHandler(result.error)
        }

        api.task.list.create
            .mutate({
                name: result.data.name
            })
            .then(() => {
                loading = false
                queryClient.invalidateQueries({ queryKey: ['taskPage'] })
                closeAllModals()
            })
            .catch((error) => {
                loading = false
                errorHandler(error)
            })
    }
</script>

<form class="space-y-4" onsubmit={handleCreateTaskList}>
    <Input label="Name" type="text" placeholder="My tasks" required />

    <Dialog.Footer>
        <Dialog.Close class={buttonVariants({ variant: 'outline' })}>Cancel</Dialog.Close>
        <Button type="submit" variant="secondary" {loading}>Create</Button>
    </Dialog.Footer>
</form>
