// apps/web/app/dashboard/_modals/RenameTaskList.tsx
'use client'

import { useRouter } from 'next/navigation'

import type { TaskList } from '@sathene/db'
import { Button, Input, useModals } from '@sathene/ui-web'

import { toast } from 'sonner'
import { z } from 'zod'
import { useZodForm } from '~/hooks/useZodForm'
import { api } from '~/lib/api'

const renameTaskListSchema = z.object({
    title: z.string().min(3)
})
type RenameTaskListSchema = z.infer<typeof renameTaskListSchema>

interface Props {
    taskList: TaskList
}

export function DashboardRenameTaskList({ taskList }: Props) {
    const { closeAllModals } = useModals()
    const router = useRouter()

    const renameTaskListMutation = api.task.list.rename.useMutation()

    const {
        handleSubmit,
        register,
        formState: { errors }
    } = useZodForm({
        schema: renameTaskListSchema,
        defaultValues: {
            title: taskList.name
        }
    })

    const handleRenameTaskList = (data: RenameTaskListSchema) => {
        renameTaskListMutation.mutate(
            {
                listId: taskList.id,
                newName: data.title
            },
            {
                onError: (err) => {
                    toast.error(err.message)
                },
                onSuccess: () => {
                    router.refresh()
                    closeAllModals()
                }
            }
        )
    }

    return (
        <form className="flex flex-col gap-4" onSubmit={handleSubmit(handleRenameTaskList)}>
            <Input
                label="New Name"
                type="text"
                required
                autoFocus
                error={errors.title?.message}
                {...register('title')}
            />

            <div className="grid grid-cols-2 gap-4 w-full">
                <Button type="button" variant="outline" onClick={closeAllModals}>
                    Cancel
                </Button>

                <Button type="submit" loading={renameTaskListMutation.isLoading}>
                    Rename
                </Button>
            </div>
        </form>
    )
}

// apps/web/src/routes/dashboard/_modals/RenameTaskList.svelte
<script lang="ts">
    import { Button, Input, buttonVariants } from '@sathene/ui'
    import { Dialog } from '@sathene/ui'

    import { api } from '$lib/api'
    import { closeAllModals } from '$lib/modals.svelte'
    import { errorHandler } from '$lib/utils'
    import { useQueryClient } from '@tanstack/svelte-query'
    import z from 'zod'

    let { listId, existingName }: { listId: string; existingName: string } = $props()

    const queryClient = useQueryClient()

    const schema = z.object({
        listId: z.ulid(),
        name: z.string().min(1)
    })

    let loading = $state(false)

    function handleRenameTaskList(e: SubmitEvent) {
        e.preventDefault()
        loading = true

        const form = new FormData(e.target as HTMLFormElement)
        const result = schema.safeParse({
            listId,
            ...Object.fromEntries(form)
        })

        if (!result.success) {
            loading = false
            throw errorHandler(result.error)
        }

        api.task.list.edit
            .mutate({
                listId,
                name: result.data.name
            })
            .then(() => {
                queryClient.invalidateQueries({ queryKey: ['taskPage'] })
                closeAllModals()
                loading = false
            })
            .catch((error) => {
                loading = false
                errorHandler(error)
            })
    }
</script>

<form class="space-y-4" onsubmit={handleRenameTaskList}>
    <Input label="Name" type="text" placeholder="My tasks" defaultValue={existingName} required />

    <Dialog.Footer>
        <Dialog.Close class={buttonVariants({ variant: 'outline' })}>Cancel</Dialog.Close>
        <Button type="submit" variant="secondary" {loading}>Rename</Button>
    </Dialog.Footer>
</form>
