// packages/ui/web/src/components/label.tsx
'use client'

import * as React from 'react'

import { cn } from '../lib/utils'
import * as LabelPrimitive from '@radix-ui/react-label'
import { cva, type VariantProps } from 'class-variance-authority'

const labelVariants = cva(
    'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70'
)

const Label = React.forwardRef<
    React.ElementRef<typeof LabelPrimitive.Root>,
    React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root> & VariantProps<typeof labelVariants>
>(({ className, ...props }, ref) => (
    <LabelPrimitive.Root ref={ref} className={cn(labelVariants(), className)} {...props} />
))
Label.displayName = LabelPrimitive.Root.displayName

export { Label }

// packages/ui/src/components/label/label.svelte
<script lang="ts">
    import { Label as LabelPrimitive } from 'bits-ui'

    import { cn } from '../../lib/utils.js'

    let {
        ref = $bindable(null),
        class: className,
        ...restProps
    }: LabelPrimitive.RootProps = $props()
</script>

<LabelPrimitive.Root
    bind:ref
    data-slot="label"
    class={cn(
        'flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
        className
    )}
    {...restProps}
/>
