// packages/ui/web/src/components/separator.tsx
'use client'

import * as React from 'react'

import { cn } from '../lib/utils'
import * as SeparatorPrimitive from '@radix-ui/react-separator'

const Separator = React.forwardRef<
    React.ElementRef<typeof SeparatorPrimitive.Root>,
    React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>
>(({ className, orientation = 'horizontal', decorative = true, ...props }, ref) => (
    <SeparatorPrimitive.Root
        ref={ref}
        decorative={decorative}
        orientation={orientation}
        className={cn(
            'shrink-0 bg-border',
            orientation === 'horizontal' ? 'h-[1px] w-full' : 'h-full w-[1px]',
            className
        )}
        {...props}
    />
))
Separator.displayName = SeparatorPrimitive.Root.displayName

export { Separator }

// packages/ui/src/components/separator/separator.svelte
<script lang="ts">
    import { Separator as SeparatorPrimitive } from 'bits-ui'

    import { cn } from '../../lib/utils.js'

    let {
        ref = $bindable(null),
        class: className,
        'data-slot': dataSlot = 'separator',
        ...restProps
    }: SeparatorPrimitive.RootProps = $props()
</script>

<SeparatorPrimitive.Root
    bind:ref
    data-slot={dataSlot}
    class={cn(
        'bg-border shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:min-h-full data-[orientation=vertical]:w-px',
        className
    )}
    {...restProps}
/>
